### ISSUE TITLE
injector 注入共享服务

### ISSUE THREAD

**Issue by qwekelly** [Eve-Sama/x6-angular-shape#1]
```typescript
register({
  content: ServiceOrchestrationPlumbNodeComponent,
  injector: Injector.create({
    providers: [
      {
        provide: PlumbNodeEventBusService,
        useFactory: () => this.nodeEventBus,
      },
    ],
    parent: this.injector,
  }),
})
```
通过这种方式给自定义的angular节点组件注入 PlumbNodeEventBusService，期待在节点里面也能使用 PlumbNodeEventBusService。但是发现好像注入不进去，控制台报错
`core.mjs:8760 Uncaught NullInjectorError: R3InjectorError(LayoutModule)[PlumbNodeEventBusService -> PlumbNodeEventBusService -> PlumbNodeEventBusService]`

- 有什么方式可以注入进去，并使得节点组件同页面组件共享一个服务吗？

**Comment by Eve-Sama** [comment]
很好的问题 但是好像没有什么特别好的办法
