### ISSUE TITLE
x6-angular-shape2.x无法触发Angular12的ngOnChanges

### ISSUE THREAD

**Issue by chenlong-io** [Eve-Sama/x6-angular-shape#2]
![QQ20231228-090321](https://github.com/Eve-Sama/x6-angular-shape/assets/10387532/14c2088a-15e3-4ffa-86a3-3b3a5d20ccf4)

我们公司是 Angular 12， x6-angular-shape 2.0.2

因为 Angular 12 版本低于 v14，当`ngArguments` 改变无法触发 `ngOnChanges`。

求个能触发的 demo 

感谢大佬！！！ 大佬万岁！！！

**Comment by Eve-Sama** [comment]
有点后悔了, 我当时应该把14以下的实现方案写下的. 因为我忘了当时想的hack方案是啥了. 我待会试下吧, 看看能不能想起来是怎么搞的.

**Comment by chenlong-io** [comment]
> 有点后悔了, 我当时应该把14以下的实现方案写下的. 因为我忘了当时想的hack方案是啥了. 我待会试下吧, 看看能不能想起来是怎么搞的.

好的大佬，在线等你

**Comment by Eve-Sama** [comment]
+个v? 在我主页有, 我本地没有12的环境 但是我大概知道怎么弄, 有点小麻烦. 为了效率我直接微信和你说吧

**Comment by Vibing** [comment]
> +个v? 在我主页有, 我本地没有12的环境 但是我大概知道怎么弄, 有点小麻烦. 为了效率我直接微信和你说吧

可以，我微信：longlonglong227

**Comment by chenlong-io** [comment]
Angular v14 以下的 ComponentRef 没有提供 setInput。所以无法触发 ngOnChanges。

时间问题，没有去仔细看 setInput 逻辑，这里介绍以下我自己的“不完美的”解决方案：

1.不要去下载 x6-angular-shape 包，直接把 x6-angular-shape 源码拿到项目用
2.我在 register 方法中多传了一个参数 ComponentFactoryResolver 用来获取动态组件。
view.ts中的renderAngularContent方法如下：
```ts
 protected renderAngularContent(): void {
    this.unmountAngularContent();
    const container = this.getNodeContainer();
    if (container) {
      const node = this.cell;
      const { injector, content, cfr } = registerInfo.get(node.shape)!;
      const viewContainerRef = injector.get(ViewContainerRef);

      if (content instanceof TemplateRef) {
        const ngArguments = this.getNgArguments();
        const embeddedViewRef = viewContainerRef.createEmbeddedView(content, { ngArguments });
        embeddedViewRef.rootNodes.forEach((node) => container.appendChild(node));
        embeddedViewRef.detectChanges();
        node.on('change:data', () => this.setInstanceInput(content, embeddedViewRef));
      } else {
        const factory = cfr.resolveComponentFactory(content);
        const componentRef = factory.create(injector);
        const insertNode = (componentRef.hostView as EmbeddedViewRef<any>).rootNodes[0] as HTMLElement;
        container.appendChild(insertNode);
        this.setInstanceInput(content, componentRef);
        node.on('change:data', () => this.setInstanceInput(content, componentRef));
        node.on('removed', () => componentRef.destroy());
      }
    }
  }
```

3.修改 setInstanceInput 给组件实例传参
```ts
private setInstanceInput(content: Content, ref: EmbeddedViewRef<any> | ComponentRef<any>): void {
    const ngArguments = this.getNgArguments();
    if (content instanceof TemplateRef) {
      const embeddedViewRef = ref as EmbeddedViewRef<any>;
      embeddedViewRef.context = { ngArguments };
    } else {
      const componentRef = ref as ComponentRef<any>;
      const instance = componentRef.instance;

      Object.keys(ngArguments).forEach((v) => {
        instance[v] = ngArguments[v];
        // componentRef.setInput(v, ngArguments[v])
      });

      componentRef.changeDetectorRef.detectChanges();
    }
  }
```
到目前为止，是可以正常渲染组件，但修改数据时无法触发 onChanges，我用的是 setter 来代替 onChanges 的效果：
```ts
@Component({
  selector: 'app-ng-node',
  templateUrl: './ng-node.component.html',
  styleUrls: ['./ng-node.component.less'],
})
export class NgNodeComponent implements OnInit {
  @Input() set data(value: any) {
    this._data = value;
    // changes
  }

  _data: any;

  constructor() {}

  ngOnInit() {}
}
```
也可以考虑用 rx.js 来达到相同的目的。

**Comment by 10229428** [comment]
@Vibing 大佬，在低版本ng中，比如我现在使用的ng9，context是只读的，要如何更新呢？
![image](https://github.com/Eve-Sama/x6-angular-shape/assets/42016535/d2d4311f-77b8-43f2-978a-8622ee788fbc)
```
export declare abstract class EmbeddedViewRef<C> extends ViewRef {
    /**
     * The context for this view, inherited from the anchor element.
     */
    abstract get context(): C;
    /**
     * The root nodes for this embedded view.
     */
    abstract get rootNodes(): any[];
}
```

**Comment by 10229428** [comment]
> @Vibing 大佬，在低版本ng中，比如我现在使用的ng9，context是只读的，要如何更新呢？ ![image](https://private-user-images.githubusercontent.com/42016535/297930377-d2d4311f-77b8-43f2-978a-8622ee788fbc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2MzAxNjMsIm5iZiI6MTcwNTYyOTg2MywicGF0aCI6Ii80MjAxNjUzNS8yOTc5MzAzNzctZDJkNDMxMWYtNzdiOC00M2YyLTk3OGEtODYyMmVlNzg4ZmJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDAyMDQyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiMmMxMzNhMzI1MWQ4NTc3ZGI5Mzg1NmI4ZWM4MTJkNzQzYTVjZThkYTkwNjE0ZTk1NTQyOTRlYTI0YjA5NzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.H3iecrM2yF10N6K83keGUDDRB6U73b-Z5PUT0tqqZ-k)
> 
> ```
> export declare abstract class EmbeddedViewRef<C> extends ViewRef {
>     /**
>      * The context for this view, inherited from the anchor element.
>      */
>     abstract get context(): C;
>     /**
>      * The root nodes for this embedded view.
>      */
>     abstract get rootNodes(): any[];
> }
> ```

改成 `embeddedViewRef.context["ngArguments"] = ngArguments;` 貌似可以了
